#!/bin/bash
#banner

printf '
   
╭━━━┳━━━┳━━━┳━━━┳━━━╮
┃╭━━┫╭━╮┃╭━╮┃╭━╮┃╭━╮┃
┃╰━━┫╰━╯┃╰━╯┃┃╱┃┃╰━╯┃
┃╭━━┫╭╮╭┫╭╮╭┫┃╱┃┃╭╮╭╯
┃╰━━┫┃┃╰┫┃┃╰┫╰━╯┃┃┃╰╮
╰━━━┻╯╰━┻╯╰━┻━━━┻╯╰━╯

                     ERROR FOR YOU
      
                        >>>>>>>>>>>>>>>>>>>>>>>>>>>'|lolcat -a -s 99 -d 30
echo '                          WELCOME TO TERMUX'|lolcat -a -s 99 -d 300

clear

printf '\e[032m


TELEGRAM: @Rohan_Trader1
OWNER OF TITAN SOFTWARE 
\n\n'
